### ISSUE TITLE
Upgrade fails

### ISSUE THREAD

**Issue by Raketenwilli** [Bubu/android-dice-game#4]
Everytime I try to upgrade the app from 1.13 to 1.14 an "unknown error" occurrences.

**Comment by Bubu** [comment]
Yes, known issue, sorry.
I described the problem here: https://github.com/Bubu/android-dice-game/releases/tag/v1.14

(The problem is that android doesn't like downgrading the targetSDK to pre-runtime permission level. But the project needs SDK 7 for #1. )

I'm working bringing the app to a more modern UI so I can bump the version again. You can wait until then or manually uninstall v1.13. Then v1.14 work again.

**Comment by Bubu** [comment]
Update will be on f-droid soon(ish).
